import { PrismaClient } from '@prisma/client';

/**
 * Seeds Chart of Accounts from 2024/2025 French school accounting PDFs.
 * All accounts set isSystem=true so they are distinguishable from user-created accounts.
 * Account codes normalised to uppercase (regex /^[A-Z0-9]{3,10}$/).
 */
export async function seedCoaAccounts(prisma: PrismaClient): Promise<void> {
	const accounts = [
		// ── Revenue accounts ──────────────────────────────────────────────────
		{
			accountCode: '701100',
			accountName: 'FACT SCO 1ER TRIMESTRE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Tuition Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701200',
			accountName: 'FACT SCO 2EME TRIMESTRE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Tuition Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701300',
			accountName: 'FACT SCO 3EME TRIMESTRE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Tuition Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701400',
			accountName: 'FACT DAI',
			type: 'REVENUE' as const,
			ifrsCategory: 'Registration Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701401',
			accountName: 'Droit de Premiere Inscription',
			type: 'REVENUE' as const,
			ifrsCategory: 'Registration Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701410',
			accountName: 'FACT FRAIS DE DOSSIER',
			type: 'REVENUE' as const,
			ifrsCategory: 'Registration Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701500',
			accountName: 'GARDERIE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701600',
			accountName: 'APS ETUDES DIRIGEES',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701700',
			accountName: 'STAGE DE NATATION',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701800',
			accountName: 'APS NATATION',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701801',
			accountName: 'APS FOOT',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701802',
			accountName: 'APS BASKET BALL',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701803',
			accountName: 'APS THEATRE EN ARABE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701806',
			accountName: 'APS ECHEC',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701808',
			accountName: 'APS ROBOTIQUE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701809',
			accountName: 'APS TAEKWONDO',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701810',
			accountName: 'APS THEATRE EN FRANCAIS',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701811',
			accountName: 'APS PING PONG',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701812',
			accountName: 'APS MANGA',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701813',
			accountName: 'APS UN JOUR UNE OEUVRE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701814',
			accountName: 'RELAXATION SPORT ET MUSIQUE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701815',
			accountName: 'APS THEATRE EN ANGLAIS',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701816',
			accountName: 'APS MATHEMATIQUES',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701817',
			accountName: 'APS DANSE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701818',
			accountName: 'APS PATISSERIE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701819',
			accountName: 'APS GYMNASTIQUE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701820',
			accountName: 'APS SANTE ET MEDECINE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701821',
			accountName: 'APS PROGRAMMATION',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701822',
			accountName: 'APS CHANSONS EN ANGLAIS',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701823',
			accountName: 'APS ESPAGNOL',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '701825',
			accountName: 'APS ART PLASTIQUE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Activities',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '707200',
			accountName: 'FOURNITURES ELEVES REMB',
			type: 'REVENUE' as const,
			ifrsCategory: 'Student Supplies',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '708100',
			accountName: 'PHOTOS DE CLASSE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Other Revenue',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '708101',
			accountName: 'AMICALE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Other Revenue',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '708150',
			accountName: 'RECETTES BAC',
			type: 'REVENUE' as const,
			ifrsCategory: 'Examination Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '708151',
			accountName: 'EPREUVES ANTICIPEES FR',
			type: 'REVENUE' as const,
			ifrsCategory: 'Examination Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '708170',
			accountName: 'RECETTES BREVET',
			type: 'REVENUE' as const,
			ifrsCategory: 'Examination Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		// Note: original code '61830EL' normalised from PDF — but the
		// task spec lists '71810R' which already has an uppercase letter.
		{
			accountCode: '71810R',
			accountName: 'LIVRE LITTERATURE REMB',
			type: 'REVENUE' as const,
			ifrsCategory: 'Student Supplies',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '718200',
			accountName: 'PERTE DETERIORATION MAN',
			type: 'REVENUE' as const,
			ifrsCategory: 'Student Supplies',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '724317',
			accountName: 'VOYAGE',
			type: 'REVENUE' as const,
			ifrsCategory: 'School Trips',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '730000',
			accountName: 'FACT EVALUATION',
			type: 'REVENUE' as const,
			ifrsCategory: 'Examination Fees',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '741001',
			accountName: 'CAISSE DE SOLIDARITE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Other Revenue',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '500011',
			accountName: 'GAIN DIFFERENCE CHANGE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Other Revenue',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '766000',
			accountName: 'GAIN DE CHANGE',
			type: 'REVENUE' as const,
			ifrsCategory: 'Finance Income',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '770000',
			accountName: 'REVENUS FINANCIERS',
			type: 'REVENUE' as const,
			ifrsCategory: 'Finance Income',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '771000',
			accountName: 'MISC REVENUES',
			type: 'REVENUE' as const,
			ifrsCategory: 'Other Revenue',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '772000',
			accountName: 'PRODUITS EXERCICES ANT',
			type: 'REVENUE' as const,
			ifrsCategory: 'Other Revenue',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '775000',
			accountName: 'PRODUITS CESSIONS ACTIF',
			type: 'REVENUE' as const,
			ifrsCategory: 'Other Revenue',
			centerType: 'PROFIT_CENTER' as const,
		},
		{
			accountCode: '785000',
			accountName: 'ROUNDING',
			type: 'REVENUE' as const,
			ifrsCategory: 'Rounding',
			centerType: 'PROFIT_CENTER' as const,
		},

		// ── Expense accounts ──────────────────────────────────────────────────
		{
			accountCode: '606001',
			accountName: 'General Expense',
			type: 'EXPENSE' as const,
			ifrsCategory: 'General Expense',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '606200',
			accountName: 'EAU',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Utilities',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '606420',
			accountName: 'LOGICIEL ADMINISTRATION',
			type: 'EXPENSE' as const,
			ifrsCategory: 'IT Expenses',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '606500',
			accountName: 'INFORMATIQUE',
			type: 'EXPENSE' as const,
			ifrsCategory: 'IT Expenses',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '613100',
			accountName: 'SCHOOL RENT',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Rent',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '615100',
			accountName: 'SCHOOL MAINTENANCE CONTRACT',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Maintenance',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '616000',
			accountName: 'INSURANCE POLICIES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Insurance',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '618100',
			accountName: 'MANUELS SCOLAIRES PRIMAIRE',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Teaching Materials',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '618110',
			accountName: 'MANUELS SCOLAIRES SEC',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Teaching Materials',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '618200',
			accountName: 'LIBRAIRIE BCD',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Teaching Materials',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '618210',
			accountName: 'LIBRAIRIE SECONDAIRE CDI',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Teaching Materials',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '618300',
			accountName: 'PUPILS SUBSCRIPTIONS BCD',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Teaching Materials',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '623100',
			accountName: 'PHOTOCOPIEUSES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Office Expenses',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '625300',
			accountName: 'CARS MAINTENANCE',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Transport',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '625600',
			accountName: 'TRAVEL INDEMNITIES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Travel',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '626000',
			accountName: 'MAIL EXPENSES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Communication',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '626100',
			accountName: 'PHONE FAX EXPENSES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Communication',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '627000',
			accountName: 'BANQUES SERVICES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Bank Charges',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '627003',
			accountName: 'MOYASAR CHARGES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Bank Charges',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '628000',
			accountName: 'AUTRES SERVICES EXTERIEURS',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Other Services',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '631300',
			accountName: 'FORMATION CONTINUE',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Training',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '631310',
			accountName: 'FORMATEUR RECU A EFIR',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Training',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '631320',
			accountName: 'MISSION ETABLISSEMENT',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Training',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '641100',
			accountName: 'FRENCH TEACHERS SALARIES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Staff Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '641120',
			accountName: 'HS FRENCH TEACHERS SAL',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Staff Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '641200',
			accountName: 'FRENCH REPLACEMENT SALARY',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Staff Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '641300',
			accountName: 'GARDERIE SALARIES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Staff Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '641400',
			accountName: 'ADMINISTRATION SALARIES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Staff Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '641401',
			accountName: 'APS SALARIES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Staff Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '641410',
			accountName: 'DEPENSE ETUDES DIRIGEES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Staff Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '641420',
			accountName: 'HS ADMINISTRATION SAL',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Staff Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '645100',
			accountName: 'GOSI PAYMENT',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Employer Charges',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '648000',
			accountName: 'AGENCE ENSEIGNEMENT FR',
			type: 'EXPENSE' as const,
			ifrsCategory: 'AEFE Fees',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '648010',
			accountName: 'CONTRIBUTION FRAIS SCO',
			type: 'EXPENSE' as const,
			ifrsCategory: 'PFC',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '648030',
			accountName: 'PRIME',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Staff Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '666000',
			accountName: 'PERTE DE CHANGE',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Finance Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '670000',
			accountName: 'PERTE FINANCIERE',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Finance Costs',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '671200',
			accountName: 'PENALITES AMENDES',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Other Expenses',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '672000',
			accountName: 'CHARGES EXERCICES ANT',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Other Expenses',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '681100',
			accountName: 'DEPRECIATION',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Depreciation',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '681700',
			accountName: 'PROVISION BAD DEBT',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Provisions',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '681750',
			accountName: 'PROVISION END OF SERVICE',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Provisions',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '685000',
			accountName: 'ARRONDISSEMENT',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Rounding',
			centerType: 'COST_CENTER' as const,
		},
		{
			accountCode: '687500',
			accountName: 'PROVISION RH NOUVELLE ECOLE',
			type: 'EXPENSE' as const,
			ifrsCategory: 'Provisions',
			centerType: 'COST_CENTER' as const,
		},
	];

	let upserted = 0;

	for (const account of accounts) {
		await prisma.chartOfAccount.upsert({
			where: { accountCode: account.accountCode },
			update: {
				accountName: account.accountName,
				type: account.type,
				ifrsCategory: account.ifrsCategory,
				centerType: account.centerType,
				isSystem: true,
				updatedBy: 1,
			},
			create: {
				accountCode: account.accountCode,
				accountName: account.accountName,
				type: account.type,
				ifrsCategory: account.ifrsCategory,
				centerType: account.centerType,
				isSystem: true,
				createdBy: 1,
				updatedBy: 1,
			},
		});
		upserted++;
	}

	console.log(`Seeded ${upserted} chart of account entries.`);
}
