import { PrismaClient } from '@prisma/client';

/**
 * Seeds the default EFIR IFRS P&L template with 14 sections and key account mappings.
 * Idempotent: deletes existing sections/mappings for the template, then recreates them.
 * Depends on seedCoaAccounts having run first (mappings reference account codes).
 */
export async function seedPnlTemplate(prisma: PrismaClient): Promise<void> {
	// Upsert the template keyed on name (name has a @@unique constraint)
	const template = await prisma.pnlTemplate.upsert({
		where: { name: 'EFIR IFRS P&L' },
		update: {
			isDefault: true,
			isSystem: true,
			updatedBy: 1,
		},
		create: {
			name: 'EFIR IFRS P&L',
			isDefault: true,
			isSystem: true,
			createdBy: 1,
			updatedBy: 1,
		},
	});

	// Delete existing sections (cascades to mappings via ON DELETE CASCADE)
	await prisma.pnlTemplateSection.deleteMany({
		where: { templateId: template.id },
	});

	// Define sections with their mappings
	const sections = [
		{
			sectionKey: 'REVENUE',
			displayLabel: 'Revenue',
			displayOrder: 10,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'POSITIVE',
			mappings: [
				{
					analyticalKey: 'TUITION_FEES',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '701100',
					monthFilter: [9, 10, 11, 12],
					displayLabel: 'Tuition T1',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'TUITION_FEES',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '701200',
					monthFilter: [1, 2, 3],
					displayLabel: 'Tuition T2',
					visibility: 'SHOW' as const,
					displayOrder: 20,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'TUITION_FEES',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '701300',
					monthFilter: [4, 5, 6],
					displayLabel: 'Tuition T3',
					visibility: 'SHOW' as const,
					displayOrder: 30,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'REG_DAI',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '701400',
					monthFilter: [],
					displayLabel: 'DAI',
					visibility: 'SHOW' as const,
					displayOrder: 40,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'REG_DPI',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '701401',
					monthFilter: [],
					displayLabel: 'DPI',
					visibility: 'SHOW' as const,
					displayOrder: 50,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'REG_FRAIS_DE_DOSSIER',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '701410',
					monthFilter: [],
					displayLabel: 'Frais de Dossier',
					visibility: 'SHOW' as const,
					displayOrder: 60,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'ACT_GARDERIE',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '701500',
					monthFilter: [],
					displayLabel: 'Daycare',
					visibility: 'SHOW' as const,
					displayOrder: 70,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'ACTIVITIES_SERVICES',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: null,
					monthFilter: [],
					displayLabel: 'Activities',
					visibility: 'GROUP' as const,
					displayOrder: 80,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'EXAMINATION_FEES',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: null,
					monthFilter: [],
					displayLabel: 'Examinations',
					visibility: 'SHOW' as const,
					displayOrder: 90,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'RENTAL_INCOME',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: null,
					monthFilter: [],
					displayLabel: 'Rental Income',
					visibility: 'GROUP' as const,
					displayOrder: 100,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
			],
		},
		{
			sectionKey: 'COST_OF_SERVICE',
			displayLabel: 'Cost of Service',
			displayOrder: 20,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'NEGATIVE',
			mappings: [
				{
					analyticalKey: 'OPEX_AGENCE',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '648000',
					monthFilter: [],
					displayLabel: 'AEFE Fees',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'OPEX_MANUELS',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '618100',
					monthFilter: [],
					displayLabel: 'Teaching Materials',
					visibility: 'SHOW' as const,
					displayOrder: 20,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
			],
		},
		{
			sectionKey: 'GROSS_PROFIT',
			displayLabel: 'Gross Profit',
			displayOrder: 30,
			isSubtotal: true,
			subtotalFormula: 'REVENUE - COST_OF_SERVICE',
			signConvention: 'POSITIVE',
			mappings: [],
		},
		{
			sectionKey: 'PFC_6PCT',
			displayLabel: 'PFC 6%',
			displayOrder: 40,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'NEGATIVE',
			mappings: [
				{
					analyticalKey: 'OPEX_CONTRIBUTION',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '648010',
					monthFilter: [],
					displayLabel: 'PFC 6%',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
			],
		},
		{
			sectionKey: 'STAFF_COSTS',
			displayLabel: 'Staff Costs',
			displayOrder: 50,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'NEGATIVE',
			mappings: [
				{
					analyticalKey: 'LOCAL_SALARIES',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '641100',
					monthFilter: [],
					displayLabel: 'French Teachers Salaries',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'LOCAL_SALARIES',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '641400',
					monthFilter: [],
					displayLabel: 'Administration Salaries',
					visibility: 'SHOW' as const,
					displayOrder: 20,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'LOCAL_SALARIES',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '641200',
					monthFilter: [],
					displayLabel: 'Replacement Salary',
					visibility: 'SHOW' as const,
					displayOrder: 30,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'ADDITIONAL_COSTS',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: null,
					monthFilter: [],
					displayLabel: 'Category Costs',
					visibility: 'GROUP' as const,
					displayOrder: 40,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'GOSI_SAUDI',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '645100',
					monthFilter: [],
					displayLabel: 'GOSI',
					visibility: 'SHOW' as const,
					displayOrder: 50,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'EMPLOYER_CHARGES',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '648030',
					monthFilter: [],
					displayLabel: 'Prime',
					visibility: 'SHOW' as const,
					displayOrder: 60,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
			],
		},
		{
			sectionKey: 'RENT',
			displayLabel: 'Rent',
			displayOrder: 60,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'NEGATIVE',
			mappings: [
				{
					analyticalKey: 'OPEX_SCHOOL_RENT',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '613100',
					monthFilter: [],
					displayLabel: 'School Rent',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
			],
		},
		{
			sectionKey: 'MAINTENANCE',
			displayLabel: 'Maintenance',
			displayOrder: 70,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'NEGATIVE',
			mappings: [
				{
					analyticalKey: 'OPEX_SCHOOL_MAINTENANCE',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '615100',
					monthFilter: [],
					displayLabel: 'School Maintenance',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
			],
		},
		{
			sectionKey: 'OTHER_OPEX',
			displayLabel: 'Other Operating Expenses',
			displayOrder: 80,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'NEGATIVE',
			mappings: [
				{
					analyticalKey: 'OPEX_GENERAL_EXPENSE',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '606001',
					monthFilter: [],
					displayLabel: 'General Expense',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'OPEX_INSURANCE',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '616000',
					monthFilter: [],
					displayLabel: 'Insurance',
					visibility: 'SHOW' as const,
					displayOrder: 20,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'OPEX_TRAVEL',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '625600',
					monthFilter: [],
					displayLabel: 'Travel & Indemnities',
					visibility: 'SHOW' as const,
					displayOrder: 30,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'OPEX_MOYASAR',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '627003',
					monthFilter: [],
					displayLabel: 'Payment Processing',
					visibility: 'SHOW' as const,
					displayOrder: 40,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'OPEX_FORMATION',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '631300',
					monthFilter: [],
					displayLabel: 'Training',
					visibility: 'SHOW' as const,
					displayOrder: 50,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
			],
		},
		{
			sectionKey: 'EBITDA',
			displayLabel: 'EBITDA',
			displayOrder: 90,
			isSubtotal: true,
			subtotalFormula: 'GROSS_PROFIT - PFC_6PCT - STAFF_COSTS - RENT - MAINTENANCE - OTHER_OPEX',
			signConvention: 'POSITIVE',
			mappings: [],
		},
		{
			sectionKey: 'DEPRECIATION',
			displayLabel: 'Depreciation',
			displayOrder: 100,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'NEGATIVE',
			mappings: [
				{
					analyticalKey: 'DEPRECIATION',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '681100',
					monthFilter: [],
					displayLabel: 'Depreciation',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
			],
		},
		{
			sectionKey: 'PROVISIONS',
			displayLabel: 'Provisions',
			displayOrder: 110,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'NEGATIVE',
			mappings: [
				{
					analyticalKey: 'EOS_PROVISION',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '681750',
					monthFilter: [],
					displayLabel: 'EOS Provision',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'IMPAIRMENT',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '681700',
					monthFilter: [],
					displayLabel: 'Bad Debt Provision',
					visibility: 'SHOW' as const,
					displayOrder: 20,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
				{
					analyticalKey: 'OPEX_PROVISION',
					analyticalKeyType: 'LINE_ITEM' as const,
					accountCode: '687500',
					monthFilter: [],
					displayLabel: 'Strategic Provisions',
					visibility: 'SHOW' as const,
					displayOrder: 30,
					profitCenterAllocation: 'HEADCOUNT' as const,
				},
			],
		},
		{
			sectionKey: 'OPERATING_PROFIT',
			displayLabel: 'Operating Profit',
			displayOrder: 120,
			isSubtotal: true,
			subtotalFormula: 'EBITDA - DEPRECIATION - PROVISIONS',
			signConvention: 'POSITIVE',
			mappings: [],
		},
		{
			sectionKey: 'NET_FINANCE',
			displayLabel: 'Net Finance',
			displayOrder: 130,
			isSubtotal: false,
			subtotalFormula: null,
			signConvention: 'POSITIVE',
			mappings: [
				{
					analyticalKey: 'FINANCE_INCOME',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '770000',
					monthFilter: [],
					displayLabel: 'Financial Income',
					visibility: 'SHOW' as const,
					displayOrder: 10,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'FINANCE_INCOME',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '766000',
					monthFilter: [],
					displayLabel: 'FX Gains',
					visibility: 'SHOW' as const,
					displayOrder: 20,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'FINANCE_COSTS',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '666000',
					monthFilter: [],
					displayLabel: 'FX Losses',
					visibility: 'SHOW' as const,
					displayOrder: 30,
					profitCenterAllocation: 'DIRECT' as const,
				},
				{
					analyticalKey: 'FINANCE_COSTS',
					analyticalKeyType: 'CATEGORY' as const,
					accountCode: '670000',
					monthFilter: [],
					displayLabel: 'Financial Losses',
					visibility: 'GROUP' as const,
					displayOrder: 40,
					profitCenterAllocation: 'DIRECT' as const,
				},
			],
		},
		{
			sectionKey: 'NET_PROFIT',
			displayLabel: 'Net Profit',
			displayOrder: 140,
			isSubtotal: true,
			subtotalFormula: 'OPERATING_PROFIT + NET_FINANCE',
			signConvention: 'POSITIVE',
			mappings: [],
		},
	];

	let totalSections = 0;
	let totalMappings = 0;

	for (const sectionDef of sections) {
		const { mappings, ...sectionData } = sectionDef;

		const section = await prisma.pnlTemplateSection.create({
			data: {
				templateId: template.id,
				sectionKey: sectionData.sectionKey,
				displayLabel: sectionData.displayLabel,
				displayOrder: sectionData.displayOrder,
				isSubtotal: sectionData.isSubtotal,
				subtotalFormula: sectionData.subtotalFormula,
				signConvention: sectionData.signConvention,
			},
		});
		totalSections++;

		for (const mapping of mappings) {
			await prisma.pnlAccountMapping.create({
				data: {
					sectionId: section.id,
					analyticalKey: mapping.analyticalKey,
					analyticalKeyType: mapping.analyticalKeyType,
					accountCode: mapping.accountCode,
					monthFilter: mapping.monthFilter,
					displayLabel: mapping.displayLabel,
					visibility: mapping.visibility,
					displayOrder: mapping.displayOrder,
					profitCenterAllocation: mapping.profitCenterAllocation,
				},
			});
			totalMappings++;
		}
	}

	console.log(
		`Seeded PnlTemplate "${template.name}" with ${totalSections} sections and ${totalMappings} mappings.`
	);
}
