export const gradeLevels = [
	{
		displayOrder: 1,
		gradeCode: 'TPS',
		gradeName: 'Toute Petite Section',
		band: 'MATERNELLE' as const,
		maxClassSize: 25,
		plancherPct: '0.7000',
		ciblePct: '0.8000',
		plafondPct: '0.9000',
	},
	{
		displayOrder: 2,
		gradeCode: 'PS',
		gradeName: 'Petite Section',
		band: 'MATERNELLE' as const,
		maxClassSize: 28,
		plancherPct: '0.7000',
		ciblePct: '0.8000',
		plafondPct: '0.9000',
	},
	{
		displayOrder: 3,
		gradeCode: 'MS',
		gradeName: 'Moyenne Section',
		band: 'MATERNELLE' as const,
		maxClassSize: 28,
		plancherPct: '0.7000',
		ciblePct: '0.8000',
		plafondPct: '0.9000',
	},
	{
		displayOrder: 4,
		gradeCode: 'GS',
		gradeName: 'Grande Section',
		band: 'MATERNELLE' as const,
		maxClassSize: 28,
		plancherPct: '0.7500',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 5,
		gradeCode: 'CP',
		gradeName: 'Cours Preparatoire',
		band: 'ELEMENTAIRE' as const,
		maxClassSize: 28,
		plancherPct: '0.7500',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 6,
		gradeCode: 'CE1',
		gradeName: 'Cours Elementaire 1',
		band: 'ELEMENTAIRE' as const,
		maxClassSize: 30,
		plancherPct: '0.7500',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 7,
		gradeCode: 'CE2',
		gradeName: 'Cours Elementaire 2',
		band: 'ELEMENTAIRE' as const,
		maxClassSize: 30,
		plancherPct: '0.7500',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 8,
		gradeCode: 'CM1',
		gradeName: 'Cours Moyen 1',
		band: 'ELEMENTAIRE' as const,
		maxClassSize: 30,
		plancherPct: '0.7500',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 9,
		gradeCode: 'CM2',
		gradeName: 'Cours Moyen 2',
		band: 'ELEMENTAIRE' as const,
		maxClassSize: 30,
		plancherPct: '0.7500',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 10,
		gradeCode: 'S6',
		gradeName: 'Sixieme',
		band: 'COLLEGE' as const,
		maxClassSize: 30,
		plancherPct: '0.8000',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 11,
		gradeCode: 'S5',
		gradeName: 'Cinquieme',
		band: 'COLLEGE' as const,
		maxClassSize: 30,
		plancherPct: '0.8000',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 12,
		gradeCode: 'S4',
		gradeName: 'Quatrieme',
		band: 'COLLEGE' as const,
		maxClassSize: 30,
		plancherPct: '0.8000',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 13,
		gradeCode: 'S3',
		gradeName: 'Troisieme',
		band: 'COLLEGE' as const,
		maxClassSize: 30,
		plancherPct: '0.8000',
		ciblePct: '0.8500',
		plafondPct: '0.9500',
	},
	{
		displayOrder: 14,
		gradeCode: 'S2',
		gradeName: 'Seconde',
		band: 'LYCEE' as const,
		maxClassSize: 35,
		plancherPct: '0.8000',
		ciblePct: '0.9000',
		plafondPct: '1.0000',
	},
	{
		displayOrder: 15,
		gradeCode: 'S1T',
		gradeName: 'Premiere / Terminale',
		band: 'LYCEE' as const,
		maxClassSize: 35,
		plancherPct: '0.8000',
		ciblePct: '0.9000',
		plafondPct: '1.0000',
	},
] as const;

export const seedAssumptions = [
	{
		key: 'vatRate',
		value: '15.0',
		unit: '%',
		section: 'tax',
		label: 'VAT Rate',
		valueType: 'PERCENTAGE' as const,
	},
	{
		key: 'discountRate',
		value: '5.0',
		unit: '%',
		section: 'financial',
		label: 'Early Payment Discount',
		valueType: 'PERCENTAGE' as const,
	},
	{
		key: 'inflationRate',
		value: '2.5',
		unit: '%',
		section: 'financial',
		label: 'Annual Inflation Rate',
		valueType: 'PERCENTAGE' as const,
	},
	{
		key: 'gosiPension',
		value: '9.75',
		unit: '%',
		section: 'social_charges',
		label: 'GOSI Pension Rate',
		valueType: 'PERCENTAGE' as const,
	},
	{
		key: 'gosiSaned',
		value: '1.50',
		unit: '%',
		section: 'social_charges',
		label: 'GOSI SANED Rate',
		valueType: 'PERCENTAGE' as const,
	},
	{
		key: 'gosiOhi',
		value: '1.00',
		unit: '%',
		section: 'social_charges',
		label: 'GOSI OHI Rate',
		valueType: 'PERCENTAGE' as const,
	},
	{
		key: 'schoolYear',
		value: '2025-26',
		unit: '',
		section: 'academic',
		label: 'Current School Year',
		valueType: 'TEXT' as const,
	},
	{
		key: 'academicWeeks',
		value: '36',
		unit: 'weeks',
		section: 'academic',
		label: 'Academic Weeks per Year',
		valueType: 'INTEGER' as const,
	},
	{
		key: 'maxClassSize',
		value: '30',
		unit: 'students',
		section: 'academic',
		label: 'Default Max Class Size',
		valueType: 'INTEGER' as const,
	},
	{
		key: 'transportFee',
		value: '5000.0000',
		unit: 'SAR',
		section: 'fees',
		label: 'Annual Transport Fee',
		valueType: 'CURRENCY' as const,
	},
	{
		key: 'registrationFee',
		value: '2500.0000',
		unit: 'SAR',
		section: 'fees',
		label: 'Registration Fee',
		valueType: 'CURRENCY' as const,
	},
	{
		key: 'insuranceFee',
		value: '500.0000',
		unit: 'SAR',
		section: 'fees',
		label: 'Insurance Fee',
		valueType: 'CURRENCY' as const,
	},
	{
		key: 'exchangeRate',
		value: '3.75',
		unit: 'SAR/USD',
		section: 'financial',
		label: 'Exchange Rate SAR/USD',
		valueType: 'DECIMAL' as const,
	},
	{
		key: 'reserveRate',
		value: '10.0',
		unit: '%',
		section: 'financial',
		label: 'Reserve Fund Rate',
		valueType: 'PERCENTAGE' as const,
	},
] as const;
